# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Download

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
    - name: test download
      run: npm run test-download 
    - name: view download folder
      run: |
        echo '==============/download/=================='
        ls ./download/
        echo '==============/download/627844/=================='
        ls ./download/627844
        echo '==============/download/627844/info.json=================='
        cat ./download/627844/info.json
